# Generated by Django 5.0.7 on 2024-07-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psln', '0002_merchcategories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MerchCategories',
        ),
    ]
