# Generated by Django 5.0.7 on 2024-07-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psln', '0004_musicmenu_musicmenudetails_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
