# Generated by Django 5.0.7 on 2024-07-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psln', '0005_songs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmenudetails',
            name='date',
            field=models.IntegerField(),
        ),
    ]
