# Generated by Django 5.0.7 on 2024-08-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psln', '0006_alter_musicmenudetails_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='image',
        ),
    ]
