# Generated by Django 5.0.7 on 2024-07-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MerchCategories',
        ),
    ]
